name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          python test_solve.py
